graph TD
    A[Enter sweep mode] --> B[Set voltage count as DAC voltage] 
    B --> C[Set DAC voltage to voltage counter]
    C --> D[Delay by __ms]
    D --> E[Read ADC measurement]
    E --> F[Send measured data to data logging task]
    F --> W[Continue]
