graph TD
    A[Enter coordinator task] --> B[Initialization] 
    B --> C[Create 4 channels, 4 DAC, 1 ADC]
    C --> D[SPI bus init] 
    D --> E[ADC init]
    E --> F[int i = 0]
    F --> G{int i < 4}
    G --> |False| K[Initialize ith DAC]
    K --> L[Initialize ith Channel]
    L --> M[i++]
    M --> G
    G --> |True| H{All initialization success}
    H --> |No| I[Error]
    H --> |Yes| J[Continue]
